import type { Metadata } from "next";
import { Bebas_Neue } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/fotter";
import { SessionProvider } from "next-auth/react"
import { auth } from "@/src/lib/auth"  // ← yeh auth.ts se aata hai, auth-edge.ts se nahi

const geistSans = Bebas_Neue({
  weight: "400",
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let session = null
  try {
    session = await auth()
  } catch (e) {
    console.error("Session fetch failed:", e)
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <SessionProvider session={session}>
          <Header />
          {children}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}